spring:
  application:
    name: userService
  #  cloud:
  #    nacos:
  #      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/ticketManagement?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aA15815249122
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yidon.www.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 7003